config/routes.rb
Worte::Application.routes.draw do
  resources :words

end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/words_controller.rb
require 'time'

class WordsController < ApplicationController
   # GET /words
   # GET /words.json
   def index
      @word = Word.new
      @word.month = distance_of_time_in_months(Date.parse("24.02.2010"), Time.now)
      
      tri_state_from_session(:german)
      tri_state_from_session(:polish)
      x = params[:german] ? Word.where("german = ?", params[:german] == "true") : Word
      y = params[:polish] ? x.where("polish = ?", params[:polish] == "true") : x
      @words = y.order('word').paginate(:page => params[:page])

      respond_to do |format|
         format.html # index.html.erb
         format.json { render json: @words }
         format.js # renders index.js.erb
      end
   end

   # GET /words/1
   # GET /words/1.json
   def show
      @word = Word.find(params[:id])

      respond_to do |format|
         format.html # show.html.erb
         format.json { render json: @word }
      end
   end

   # GET /words/new
   # GET /words/new.json
   def new
      @word = Word.new

      respond_to do |format|
         format.html # new.html.erb
         format.json { render json: @word }
      end
   end

   # GET /words/1/edit
   def edit
      @word = Word.find(params[:id])
   end

   # POST /words
   # POST /words.json
   def create
      @word = Word.new(params[:word])

      respond_to do |format|
         if @word.save
            format.html { redirect_to Word, notice: 'Wort erfolgreich angelegt.' }
            format.json { render json: @word, status: :created, location: @word }
         else
            format.html { render action: "new" }
            format.json { render json: @word.errors, status: :unprocessable_entity }
         end
      end
   end

   # PUT /words/1
   # PUT /words/1.json
   def update
      @word = Word.find(params[:id])

      respond_to do |format|
         if @word.update_attributes(params[:word])
            format.html { redirect_to Word, notice: 'Wort wurde erfolgreich geaendert.' }
            format.json { head :no_content }
         else
            format.html { render action: "edit" }
            format.json { render json: @word.errors, status: :unprocessable_entity }
         end
      end
   end

   # DELETE /words/1
   # DELETE /words/1.json
   def destroy
      @word = Word.find(params[:id])
      @word.destroy

      respond_to do |format|
         format.html { redirect_to words_url, notice: 'Wort wurde erfolgreich geloescht.' }
         format.json { head :no_content }
      end
   end

   private

   def tri_state_from_session param
      params[param] = session[param] if session[param] and not params[param]
      params[param] = nil if params[param] == 'none'
      session[param] = params[param]
   end

   def distance_of_time_in_months from_time, to_time
      years = to_time.year - from_time.year
      months = to_time.month - from_time.month
      days = to_time.day - from_time.day
      return years * 12 + months + (days < 0 ? -1 : 0)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
   # nil->"true"->"false"->"none"->"true"...
   def tri_state_href param
      return params[param] ? params[param] == "true" ?  words_path(param => 'false') :  words_path(param => 'none') :  words_path(param => 'true')
   end

   def tri_state_class param
      return params[param] ? params[param] == "true" ?  "toggle_true" :  "toggle_false" :  "toggle_none"
   end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="round">
    <ul>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Worte</title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application" %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/words/_filter.html.erb
<%= link_to "German (toggle)",
        words_path(:german => true),
        :remote => true,
        :id => 'toggle' %>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>
  <tr>
  <th>
    <%= f.label :wort %>
  </th>
  <th>
    <%= f.text_field :word %>
  </th>
  <th>
    <%= f.label :aussprache %>
  </th>
  <th>
    <%= f.text_field :spelling %>
  </th>
  </tr>
  <tr>
  <th>
    <%= f.label :kommentar %>
  </th>
  <th>
    <%= f.text_field :comment %>
  </th>
  <th>
    <%= f.label :monat %>
  </th>
  <th>
    <%= f.number_field :month %>
  </th>
  </tr>
  <tr>
  <th>
    <%= f.label :polnisch %>
  </th>
  <th>
    <%= f.check_box :polish %>
  </th>
  <th>
    <%= f.label :deutsch %>
  </th>
  <th>
    <%= f.check_box :german %>
  </tr>
  </th>
</table>
    <%= f.submit %>
<% end %>

app/views/words/_word.html.erb
<tr>
    <td><%= word.word %></td>
    <td><%= word.spelling %></td>
    <td><%= word.comment %></td>
    <td><%= word.month %></td>
    <td><%= word.polish %></td>
    <td><%= word.german %></td>
    <td><%= link_to 'Aendern', edit_word_path(word) %></td>
    <td><%= link_to 'Loeschen', word, confirm: 'Are you sure?', method: :delete %></td>
</tr>

app/views/words/edit.html.erb
<div class="change_word_block">

<h1>Wort aendern</h1>

<%= render 'form' %>

</div>

<%= link_to 'Zurueck', words_path %>

app/views/words/index.html.erb
<div class="new_word_block">
<h1>Neues Wort</h1>

<%= render 'form' %>
</div>

<br />

<div class="word_list_block">
<h1>Wortliste</h1>

<div class="digg_pagination">
    <%= will_paginate @words %>
</div>

<table>
  <tr>
    <th>Wort</th>
    <th>Aussprache</th>
    <th>Kommentar</th>
    <th>Monat</th>
    <th>
<%= link_to "Polnisch",
        words_path(:polish => true),
        :remote => true,
        :id => 'polish_toggle',
        :class=>"toggle_none" %>
</th>
    <th>
<%= link_to "Deutsch",
        words_path(:german => true),
        :remote => true,
        :id => 'german_toggle',
        :class=>"toggle_none"  %>
</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <ul id = "words"
    <%= render @words %>
  </ul>
</table>

<div class="digg_pagination">
    <%= will_paginate @words %>
</div>
<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @posts %>
    </div>
</div>
</div>

<br />

app/views/words/index.js.erb
<% clazz = tri_state_class(:polish) %>
<% href = tri_state_href(:polish) %>
$("#polish_toggle").attr("class", "<%= clazz %>");
$("#polish_toggle").attr("href", "<%= href %>");

<% clazz = tri_state_class(:german) %>
<% href = tri_state_href(:german) %>
$("#german_toggle").attr("class", "<%= clazz %>");
$("#german_toggle").attr("href", "<%= href %>");

$("#words").html('<%= escape_javascript(render @words) %>');

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Word:</b>
  <%= @word.word %>
</p>

<p>
  <b>Language:</b>
  <%= @word.language %>
</p>


<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>